export const SERVICE_CATEGORIES = [
  {
    id: "oil",
    name: "Vidange d'huile",
    icon: "🛢️",
    description: "Changement d'huile moteur et filtre",
  },
  {
    id: "tires-winter",
    name: "Pneus d'hiver",
    icon: "❄️",
    description: "Installation, entreposage et vente de pneus d'hiver",
  },
  {
    id: "tires-summer",
    name: "Pneus d'été / toutes saisons",
    icon: "☀️",
    description: "Installation et vente de pneus d'été et toutes saisons",
  },
  {
    id: "brakes",
    name: "Freins",
    icon: "🔴",
    description: "Inspection, réparation et remplacement des freins",
  },
  {
    id: "ac",
    name: "Climatisation",
    icon: "💨",
    description: "Recharge, réparation et entretien de l'air climatisé",
  },
  {
    id: "engine",
    name: "Mécanique générale",
    icon: "🔧",
    description: "Réparations moteur, courroie de distribution, etc.",
  },
  {
    id: "inspection",
    name: "Inspection mécanique",
    icon: "🔍",
    description: "Inspection pré-achat et inspection générale",
  },
  {
    id: "battery",
    name: "Batterie",
    icon: "🔋",
    description: "Test, remplacement et chargement de batterie",
  },
  {
    id: "transmission",
    name: "Transmission",
    icon: "⚙️",
    description: "Réparation et entretien de la boîte de vitesses",
  },
  {
    id: "bodywork",
    name: "Carrosserie",
    icon: "🚗",
    description: "Débosselage, peinture et réparation carrosserie",
  },
  {
    id: "alignment",
    name: "Alignement",
    icon: "📐",
    description: "Alignement des roues et géométrie",
  },
  {
    id: "suspension",
    name: "Suspension & direction",
    icon: "🌀",
    description: "Amortisseurs, ressorts et direction",
  },
  {
    id: "electrical",
    name: "Électrique / Électronique",
    icon: "⚡",
    description: "Diagnostic électronique, alternateur, démarreur",
  },
  {
    id: "exhaust",
    name: "Système d'échappement",
    icon: "💨",
    description: "Réparation et remplacement de l'échappement",
  },
  {
    id: "cooling",
    name: "Système de refroidissement",
    icon: "🌡️",
    description: "Radiateur, thermostat et liquide de refroidissement",
  },
  {
    id: "detailing",
    name: "Détailing & lavage",
    icon: "✨",
    description: "Nettoyage intérieur/extérieur, polish, céramique",
  },
  {
    id: "ev",
    name: "Véhicule électrique (VE)",
    icon: "🔌",
    description: "Entretien et réparation spécialisés véhicules électriques",
  },
  {
    id: "glass",
    name: "Vitres & pare-brise",
    icon: "🪟",
    description: "Remplacement et réparation de vitres",
  },
  {
    id: "timing",
    name: "Courroie de distribution",
    icon: "🔩",
    description: "Remplacement courroie ou chaîne de distribution",
  },
  {
    id: "clutch",
    name: "Embrayage",
    icon: "🔄",
    description: "Remplacement d'embrayage et boîte manuelle",
  },
  {
    id: "preventive",
    name: "Entretien préventif",
    icon: "📋",
    description: "Révision 30 000 km, 60 000 km, 100 000 km",
  },
  {
    id: "bearing",
    name: "Roulements de roue",
    icon: "⭕",
    description: "Remplacement de roulements et moyeux",
  },
  {
    id: "fuel",
    name: "Système de carburant",
    icon: "⛽",
    description: "Nettoyage injecteurs, pompe à carburant, filtre",
  },
  {
    id: "rust",
    name: "Protection contre la rouille",
    icon: "🛡️",
    description: "Traitement antirouille et protection de carrosserie",
  },
];

export const QUEBEC_CITIES = [
  "Montréal",
  "Québec",
  "Laval",
  "Longueuil",
  "Sherbrooke",
  "Saguenay",
  "Lévis",
  "Trois-Rivières",
  "Terrebonne",
  "Saint-Jean-sur-Richelieu",
  "Repentigny",
  "Brossard",
  "Drummondville",
  "Saint-Jérôme",
  "Blainville",
  "Granby",
  "Mirabel",
  "Châteauguay",
  "Mascouche",
  "Victoriaville",
  "Saint-Hyacinthe",
  "Dollard-des-Ormeaux",
  "Rimouski",
  "Rouyn-Noranda",
  "Val-d'Or",
  "Gatineau",
  "Alma",
  "Baie-Comeau",
  "Sept-Îles",
  "Shawinigan",
  "Joliette",
  "Sorel-Tracy",
  "Rivière-du-Loup",
  "Thetford Mines",
];
