/**
 * Génère 104 conseils auto (2/semaine × 52 semaines) pour l'année courante.
 * Lance avec : npx tsx --env-file=.env.local scripts/seed_tips.ts
 */
import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter } as any);

// Retourne le prochain lundi à partir de la date donnée (inclus si lundi)
function nextMonday(from: Date): Date {
  const d = new Date(from);
  d.setHours(8, 0, 0, 0);
  const day = d.getDay(); // 0=dim, 1=lun
  const diff = day === 1 ? 0 : (8 - day) % 7;
  d.setDate(d.getDate() + diff);
  return d;
}

const TIPS: { title: string; content: string; category: string; season: string }[] = [
  // ── HIVER ──────────────────────────────────────────────────────────────────
  { season:"hiver", category:"saisonnier", title:"Changez vos pneus d'hiver avant les premières neiges", content:"Au Québec, les pneus d'hiver sont obligatoires du 1er décembre au 15 mars. N'attendez pas la première tempête pour prendre rendez-vous : les garages se remplissent rapidement en octobre–novembre. Idéalement, planifiez le changement dès que les températures descendent régulièrement sous 7 °C — c'est là que le caoutchouc d'été commence à durcir et à perdre en adhérence." },
  { season:"hiver", category:"securite", title:"Testez votre batterie avant l'hiver", content:"Le froid réduit jusqu'à 60 % la capacité d'une batterie vieillissante. Une batterie de plus de 3 ans mérite un test de charge gratuit chez votre garagiste. Signe avant-coureur : le moteur tourne plus lentement au démarrage. Ne vous retrouvez pas en panne à -25 °C." },
  { season:"hiver", category:"entretien", title:"Vérifiez votre liquide de refroidissement antigel", content:"Le liquide de refroidissement protège votre moteur contre le gel et la corrosion. Vérifiez sa concentration avec un réfractomètre (votre garagiste peut le faire en quelques secondes). Pour le Québec, une protection jusqu'à -40 °C est recommandée. Changez-le si sa couleur est marron ou s'il date de plus de 2 ans." },
  { season:"hiver", category:"securite", title:"Balais d'essuie-glaces : passez aux versions hiver", content:"Les balais d'essuie-glaces standards accumulent la neige et le verglas dans leur armature, ce qui réduit leur efficacité. Les balais hiver ont une gaine caoutchouc qui les protège. Changez-les avant les premières neiges et vérifiez le niveau de lave-glace antigel — jamais d'eau pure en hiver." },
  { season:"hiver", category:"economie", title:"Évitez de laisser tourner votre moteur au ralenti", content:"Contrairement à la croyance populaire, un moteur moderne n'a besoin que de 30 secondes de préchauffage avant de rouler doucement. Laisser tourner plus longtemps dilue l'huile avec de l'essence non brûlée, pollue inutilement et est interdit dans de nombreuses municipalités québécoises (règlement municipal)." },
  { season:"hiver", category:"entretien", title:"Rouille et sel : protégez le dessous de caisse", content:"Le sel de déglaçage est l'ennemi numéro un de la carrosserie québécoise. Un traitement antirouille annuel sur le dessous de caisse (injection de cire dans les cavités) peut prolonger la vie de votre véhicule de plusieurs années. Planifiez-le en automne, avant les premières applications de sel." },
  { season:"hiver", category:"securite", title:"Distance de freinage sur glace : ×10 par rapport au sec", content:"Sur glace, la distance de freinage d'un véhicule à 50 km/h peut dépasser 150 mètres — soit 10 fois plus que sur route sèche. Adaptez votre vitesse et maintenez une distance de sécurité de 6 à 8 secondes derrière le véhicule précédent. Vos pneus d'hiver aident, mais ne font pas de miracles." },
  { season:"hiver", category:"entretien", title:"Vérifiez la pression de vos pneus par temps froid", content:"Pour chaque baisse de 10 °C, la pression des pneus chute d'environ 1 PSI. Un pneu sous-gonflé consomme plus d'essence, s'use irrégulièrement et offre une moins bonne tenue de route. Vérifiez la pression à froid chaque semaine en hiver — les valeurs recommandées sont dans le manuel du véhicule ou sur l'autocollant dans l'encadrement de la portière conducteur." },
  { season:"hiver", category:"securite", title:"Kit d'urgence hivernal : gardez-le dans votre coffre", content:"En cas de panne par temps froid, un kit d'urgence peut sauver des vies : câbles de démarrage, pelle pliante, grattoir à glace, couverture thermique, corde de remorquage, bougie et briquets, eau et biscuits énergétiques. En voiture sur de longues distances en hiver, c'est un réflexe à avoir." },
  { season:"hiver", category:"entretien", title:"Huile moteur : choisissez la bonne viscosité pour l'hiver", content:"Par grand froid, une huile trop épaisse circule mal au démarrage et protège moins bien le moteur. Vérifiez votre manuel — beaucoup de constructeurs recommandent une huile 0W-20 ou 5W-30 pour les hivers canadiens. Profitez de votre changement d'huile d'automne pour passer à la viscosité hivernale recommandée." },

  // ── PRINTEMPS ──────────────────────────────────────────────────────────────
  { season:"printemps", category:"saisonnier", title:"Changez vos pneus d'hiver dès que possible", content:"Dès que les températures se stabilisent au-dessus de 7 °C, remettez vos pneus d'été. Les pneus d'hiver s'usent rapidement sur route chaude et sèche, et leur adhérence en virage est inférieure. Planifiez tôt — les garages débordent en mars–avril. Et faites vérifier l'usure et la pression en même temps." },
  { season:"printemps", category:"entretien", title:"Vérification complète après l'hiver : les 8 points essentiels", content:"L'hiver est brutal pour votre voiture. Après la saison, faites vérifier : 1) freins (le sel accélère la corrosion), 2) pneus et pression, 3) alignement (les nids-de-poule faussent la géométrie), 4) amortisseurs, 5) liquide de direction, 6) niveau d'huile, 7) filtre à air, 8) essuie-glaces. Un bilan de printemps complet évite les mauvaises surprises en été." },
  { season:"printemps", category:"entretien", title:"Nids-de-poule : vérifiez l'alignement et la suspension", content:"Les hivers québécois créent d'innombrables nids-de-poule qui malmènent la suspension et l'alignement de votre véhicule. Si vous ressentez des vibrations au volant, une dérive d'un côté, ou des bruits inhabituels en roulant sur des bosses, faites vérifier l'alignement et les rotules. Ignorer ces symptômes accélère l'usure des pneus." },
  { season:"printemps", category:"entretien", title:"Nettoyez votre véhicule après l'hiver — y compris le dessous", content:"Le sel et les abrasifs accumulés tout l'hiver sur votre carrosserie et dessous de caisse continuent de corroder le métal même après la fonte des neiges. Un lavage à pression du dessous de caisse au printemps est essentiel. Profitez-en pour inspecter visuellement pour toute rouille naissante." },
  { season:"printemps", category:"economie", title:"Revérifiez la pression des pneus au retour des beaux jours", content:"La hausse de température printanière gonfle légèrement les pneus. Un pneu surgonflé s'use au centre et adhère moins bien. Revérifiez la pression à froid (le matin) dès que les températures changent significativement. Cela prend 2 minutes et peut vous faire économiser en carburant et en usure de pneus." },
  { season:"printemps", category:"entretien", title:"Changez votre filtre à air au printemps", content:"Après l'hiver, votre filtre à air peut être chargé de sel, de sable et de poussière. Un filtre à air encrassé réduit les performances du moteur et augmente la consommation de carburant. Le remplacement est simple et peu coûteux — vérifiez-le tous les 20 000 km ou une fois par an." },
  { season:"printemps", category:"entretien", title:"Vidange de printemps : profitez-en pour tout vérifier", content:"Si vous n'avez pas fait de vidange à l'automne, le printemps est le bon moment. L'huile qui a subi les démarrages à froid de l'hiver mérite d'être changée. Profitez-en pour demander une inspection des courroies, des durites et du niveau de tous les liquides. Prévenir coûte toujours moins cher que réparer." },

  // ── ÉTÉ ───────────────────────────────────────────────────────────────────
  { season:"ete", category:"saisonnier", title:"Climatisation : faites-la vérifier avant les canicules", content:"Si votre climatisation souffle de l'air tiède ou fait un bruit inhabituel, ne remettez pas la vérification à plus tard. Une recharge de fluide frigorigène ou un remplacement du compresseur coûte beaucoup moins cher quand c'est planifié. Les garages sont surchargés lors des premières canicules." },
  { season:"ete", category:"securite", title:"Chaleur et pneus : les dangers du surgonflage estival", content:"Par forte chaleur, la pression des pneus peut augmenter de 4 à 6 PSI. Un pneu déjà bien gonflé peut dépasser sa limite de sécurité. Si votre véhicule est garé au soleil toute la journée, vérifiez la pression le matin à froid. En voyage, arrêtez-vous pour laisser refroidir les pneus si vous avez roulé longtemps à haute vitesse." },
  { season:"ete", category:"entretien", title:"Liquide de refroidissement : vérifiez le niveau avant les grandes chaleurs", content:"En été, le risque de surchauffe du moteur est plus élevé. Vérifiez le niveau du liquide de refroidissement dans le vase d'expansion (jamais sur le radiateur à chaud !). Si votre voiture surchauffe souvent en circulation lente ou en montée, faites vérifier le thermostat et le ventilateur électrique." },
  { season:"ete", category:"economie", title:"Climatisation vs fenêtres ouvertes : lequel consomme moins ?", content:"En ville à basse vitesse, ouvrir les fenêtres consomme moins que la climatisation. Sur autoroute à plus de 80 km/h, la résistance aérodynamique des fenêtres ouvertes dépasse la consommation de la clim. Utilisez la clim avec modération, évitez le recirculation à 100 % (mauvais pour l'air intérieur), et garez-vous à l'ombre quand possible." },
  { season:"ete", category:"securite", title:"Voyage estival : vérifiez votre véhicule avant de partir", content:"Avant un long trajet d'été : vérifiez les pneus (pression + usure), les niveaux (huile, refroidissement, lave-glace), les freins, les essuie-glaces et assurez-vous que la roue de secours est en bon état. Un bilan pré-voyage chez votre garagiste prend moins d'une heure et peut vous éviter une panne loin de chez vous." },
  { season:"ete", category:"entretien", title:"Entreposage des pneus d'hiver : les bonnes pratiques", content:"Des pneus d'hiver bien entreposés durent plus longtemps. Gardez-les dans un endroit frais, sec et à l'abri du soleil direct. Empilez-les à plat s'ils ne sont pas montés sur jantes, debout s'ils le sont. Évitez le contact avec des solvants ou de l'ozone (moteurs électriques à proximité). Marquez la position (AV/AR) pour la prochaine saison." },
  { season:"ete", category:"entretien", title:"Freins : les signaux d'alerte à ne pas ignorer", content:"En été, avec les routes sèches et les vitesses plus élevées, les freins sont sollicités davantage. Méfiez-vous de : vibrations au freinage (disques voilés), bruit de grattement (plaquettes usées), pédale molle (liquide de frein à changer), ou dérive d'un côté. Un freinage défaillant est une urgence — consultez votre garagiste sans attendre." },
  { season:"ete", category:"economie", title:"Adoptez l'écoconduite pour économiser jusqu'à 25 % de carburant", content:"L'écoconduite est simple et efficace : anticipez les freinages pour ne pas accélérer inutilement, maintenez une vitesse constante sur autoroute (le régulateur aide), évitez les accélérations brusques, et réduisez votre vitesse. Passer de 120 à 100 km/h sur autoroute peut réduire votre consommation de 20 %. Calculé sur un an, l'économie est significative." },

  // ── AUTOMNE ────────────────────────────────────────────────────────────────
  { season:"automne", category:"saisonnier", title:"Planifiez votre changement de pneus d'hiver dès septembre", content:"Les plages de rendez-vous pour le changement de pneus d'hiver disparaissent en quelques jours en octobre. Appelez votre garagiste dès la rentrée pour réserver votre créneau. Idéalement, choisissez une date où les températures commencent à passer sous 7 °C régulièrement — c'est le signal que le caoutchouc d'été perd son efficacité." },
  { season:"automne", category:"entretien", title:"Antirouille automnal : le moment idéal pour protéger votre véhicule", content:"L'automne est la meilleure période pour appliquer un traitement antirouille : avant le sel, mais assez chaud pour que le produit pénètre bien dans les cavités. Un traitement annuel par injection de cire dans les bas de caisse et les cavités de portes peut doubler la durée de vie de votre carrosserie dans les conditions québécoises." },
  { season:"automne", category:"entretien", title:"Vérifiez votre batterie avant les premiers grands froids", content:"Une batterie de 3 à 5 ans peut être testée gratuitement chez la plupart des garagistes. En automne, avant que le froid ne réduise sa capacité, c'est le meilleur moment pour savoir si elle tiendra un hiver de plus. Le remplacement préventif coûte bien moins cher qu'un dépannage d'urgence en janvier." },
  { season:"automne", category:"entretien", title:"Remplissez votre réservoir de lave-glace antigel", content:"Oubliez le lave-glace estival à partir d'octobre. Passez à une formule antigel (-40 °C pour le Québec). Ne diluez jamais avec de l'eau — vous risquez de bloquer le système de lave-glace par gel. Gardez un bidon de rechange dans le coffre : en hiver, vous consommez beaucoup plus de lave-glace qu'en été." },
  { season:"automne", category:"securite", title:"Feuilles mouillées = surface aussi glissante que la glace", content:"En automne, des feuilles mortes mouillées sur la route peuvent être aussi glissantes que du verglas. Méfiez-vous particulièrement dans les virages, les ronds-points et devant les passages piétons. Réduisez votre vitesse et augmentez votre distance de sécurité. Vos pneus d'été n'adhèrent pas sur cette surface." },
  { season:"automne", category:"entretien", title:"Changez vos essuie-glaces avant la saison froide", content:"Les balais d'essuie-glaces durent généralement 12 à 18 mois. L'automne est le bon moment pour les remplacer, avant qu'ils ne doivent faire face à neige, verglas et pluie froide. Choisissez des balais hiver — leur gaine protectrice évite l'accumulation de glace dans l'armature." },

  // ── TOUTE L'ANNÉE ──────────────────────────────────────────────────────────
  { season:"toute_annee", category:"entretien", title:"Vidange d'huile : respectez l'intervalle recommandé", content:"L'huile moteur se dégrade avec le temps et les kilomètres. Elle lubrifie, refroidit et nettoie le moteur — une huile usée fait tout cela moins bien. Consultez votre manuel : beaucoup de véhicules récents recommandent un changement tous les 8 000 à 12 000 km. Ignorer les vidanges est la cause numéro un de l'usure prématurée des moteurs." },
  { season:"toute_annee", category:"securite", title:"Vérifiez votre pression de pneus chaque mois", content:"Un pneu correctement gonflé consomme moins d'essence, s'use de façon uniforme et offre une meilleure tenue de route. La vérification prend moins de 5 minutes avec un manomètre à moins de 20 $. Faites-la à froid (après 3h à l'arrêt ou moins de 3 km à vitesse réduite). Les valeurs recommandées sont dans le manuel ou sur la portière." },
  { season:"toute_annee", category:"entretien", title:"Liquide de frein : changez-le tous les 2 ans", content:"Le liquide de frein est hygroscopique — il absorbe l'humidité de l'air avec le temps. Cette humidité abaisse son point d'ébullition et peut causer une « vapeur lock » lors d'un freinage intense. Peu coûteux à changer (moins de 100 $), c'est un entretien trop souvent oublié. Vérifiez aussi son niveau dans le bocal." },
  { season:"toute_annee", category:"securite", title:"Angles morts : la vérification qui sauve des vies", content:"Plus de 35 % des accidents de changement de voie impliquent un angle mort. Ajustez correctement vos rétroviseurs : vous ne devriez voir votre propre voiture qu'en tournant légèrement la tête. Complétez avec un regard rapide par-dessus l'épaule avant chaque changement de voie. Les capteurs d'angle mort des véhicules récents sont un complément, pas un remplacement." },
  { season:"toute_annee", category:"economie", title:"Gonflage à l'azote : mythe ou réalité ?", content:"L'azote est présenté comme supérieur à l'air pour gonfler les pneus car il maintient mieux la pression dans le temps et n'absorbe pas l'humidité. En pratique, l'air est composé à 78 % d'azote déjà. Le bénéfice réel est marginal pour un usage normal. Votre argent est mieux investi dans des vérifications régulières de pression." },
  { season:"toute_annee", category:"entretien", title:"Courroie de distribution : l'entretien qu'on ne voit pas venir", content:"La courroie de distribution synchronise le moteur — si elle casse, les dégâts peuvent être catastrophiques (moteur à remplacer). Elle n'émet aucun symptôme avant de céder. Consultez votre carnet d'entretien : la plupart des constructeurs recommandent un remplacement entre 100 000 et 160 000 km. C'est coûteux mais incomparablement moins qu'un moteur neuf." },
  { season:"toute_annee", category:"securite", title:"Fatigue au volant : aussi dangereux que l'alcool", content:"Conduire après 24h sans sommeil équivaut à conduire avec 1,0 g/L d'alcool dans le sang — au-delà du seuil légal. Signes précurseurs : clignotements fréquents, difficulté à rester dans la voie, perte de souvenir des derniers kilomètres. Arrêtez-vous dès que vous ressentez ces symptômes. Une sieste de 20 minutes en aire de repos est toujours préférable." },
  { season:"toute_annee", category:"entretien", title:"Amortisseurs : comment savoir s'ils sont usés", content:"Des amortisseurs usés réduisent la tenue de route, augmentent les distances de freinage et accélèrent l'usure des pneus. Test simple : appuyez fort sur un coin du véhicule et relâchez — il doit rebondir une seule fois. Si ça oscille plusieurs fois, les amortisseurs sont à vérifier. À remplacer par paires (les deux avant ou les deux arrière)." },
  { season:"toute_annee", category:"economie", title:"Régulateur de vitesse : un allié méconnu pour l'économie de carburant", content:"Sur autoroute, maintenir une vitesse parfaitement constante est quasi impossible sans régulateur. Les légères variations de vitesse que vous faites inconsciemment consomment plus d'essence. Utiliser le régulateur à 100 km/h peut réduire votre consommation de 5 à 10 % sur un long trajet. Évitez-le par mauvais temps ou en circulation dense." },
  { season:"toute_annee", category:"entretien", title:"Bougies d'allumage : l'entretien que les automobilistes oublient", content:"Des bougies usées provoquent des ratés d'allumage, augmentent la consommation et les émissions. La plupart des véhicules récents ont des bougies longue durée (60 000 à 100 000 km), mais vérifiez votre manuel. Symptômes d'usure : démarrages difficiles, à-coups à l'accélération, voyant « check engine »." },
  { season:"toute_annee", category:"securite", title:"Rétroviseur intérieur éblouissant : utilisez le mode nuit", content:"La plupart des rétroviseurs intérieurs ont une petite languette à leur base ou se règlent automatiquement pour passer en mode anti-éblouissement la nuit. Les véhicules récents ont un rétroviseur antireflet automatique. Si vous êtes ébloui par les phares derrière vous, utilisez cette fonction — votre vision nocturne en dépend." },
  { season:"toute_annee", category:"entretien", title:"Filtre à habitacle : changez-le une fois par an", content:"Le filtre à habitacle (filtre de climatisation) retient les pollens, poussières et particules fines qui entrent dans votre véhicule. Un filtre encrassé réduit le débit d'air et peut favoriser les mauvaises odeurs. Peu coûteux (20 à 40 $), il se change facilement — souvent derrière la boîte à gants. À renouveler chaque année, idéalement au printemps." },
  { season:"toute_annee", category:"economie", title:"Poids inutile dans le coffre : ça coûte de l'argent", content:"Chaque 50 kg supplémentaires dans votre véhicule augmentent la consommation d'environ 2 %. Videz votre coffre des objets que vous transportez sans raison : matériaux de construction, équipements sportifs hors saison, etc. Sur 20 000 km annuels, l'économie peut représenter plusieurs pleins d'essence." },
  { season:"toute_annee", category:"securite", title:"Voyant « check engine » : ne l'ignorez pas", content:"Le voyant moteur (check engine) peut signaler quelque chose d'anodin comme un bouchon de réservoir mal fermé, ou quelque chose de sérieux comme une défaillance du catalyseur. La seule façon de le savoir est une lecture de codes OBD-II. Beaucoup de garages le font gratuitement. Un problème détecté tôt coûte presque toujours moins cher à réparer." },
  { season:"toute_annee", category:"entretien", title:"Liquide de direction assistée : vérifiez-le régulièrement", content:"Un niveau bas de liquide de direction assistée peut provoquer un bruit de pompe et une direction plus lourde. Vérifiez le bocal (souvent sous le capot côté conducteur) à froid. Si le niveau baisse régulièrement, il y a peut-être une fuite à diagnostiquer. Certains véhicules récents ont une direction électrique et n'ont pas de liquide." },
  { season:"toute_annee", category:"achat", title:"Inspection pré-achat : ne jamais acheter sans", content:"Avant d'acheter un véhicule d'occasion, faites-le inspecter par un mécanicien indépendant — pas celui du vendeur. Une inspection complète coûte entre 100 et 150 $ et peut révéler des problèmes cachés valant des milliers. Vérifiez aussi l'historique avec CARFAX ou CarProof : accidents, kilométrage déclaré, nombre de propriétaires." },
  { season:"toute_annee", category:"electrique", title:"Véhicule électrique : comment préserver la batterie", content:"La batterie d'un VE se dégrade plus vite si elle est régulièrement chargée à 100 % ou déchargée sous 20 %. Maintenez-la entre 20 et 80 % pour prolonger sa durée de vie (réservez la charge à 100 % pour les longs trajets). Évitez aussi la charge rapide DC quotidienne — la charge de niveau 2 (à domicile) est plus douce pour les cellules." },
  { season:"toute_annee", category:"entretien", title:"Transmission automatique : le liquide qu'on oublie trop souvent", content:"Le liquide de transmission automatique lubrifie et refroidit la boîte de vitesses. Contrairement à ce que prétend le marketing « à vie », ce liquide se dégrade. Un changement vers 60 000 à 80 000 km prévient des pannes coûteuses. Symptômes d'usure : à-coups au passage des vitesses, glissement, ou liquide rouge vif devenu brun foncé." },
  { season:"toute_annee", category:"securite", title:"Roue de secours : vérifiez qu'elle est opérationnelle", content:"Quand avez-vous vérifié votre roue de secours pour la dernière fois ? Une roue à plat au bord de la route est déjà stressante — découvrir que votre secours est aussi à plat l'est encore plus. Vérifiez la pression de la roue de secours deux fois par an. Si votre véhicule n'a qu'un kit anti-crevaison, assurez-vous qu'il est encore utilisable." },
  { season:"toute_annee", category:"entretien", title:"Roulements de roue : le bruit qu'on ne devrait pas ignorer", content:"Un roulement de roue usé produit un bourdonnement qui change avec la vitesse, parfois confondu avec le bruit des pneus. Pour distinguer : si le bruit change quand vous tournez légèrement le volant sur autoroute, c'est probablement un roulement. À négliger, un roulement défaillant peut entraîner une roue bloquée ou pire — à réparer rapidement." },
  { season:"toute_annee", category:"economie", title:"Démarrage à froid : les premières minutes comptent", content:"Juste après un démarrage, le moteur tourne sans toute la protection de l'huile (elle est encore dans le carter). Évitez les accélérations brusques pendant les 2 à 3 premières minutes. Roulez doucement. Ce réflexe, appliqué sur des années, réduit significativement l'usure du moteur." },
  { season:"toute_annee", category:"achat", title:"Financement auto : comparez le coût total, pas la mensualité", content:"Les concessionnaires savent que beaucoup de clients se focalisent sur la mensualité. Un financement sur 84 mois semble abordable mais coûte souvent plus cher qu'un achat comptant ou un prêt court. Comparez toujours le coût total incluant les intérêts. Un prêt bancaire pré-approuvé vous donne aussi un meilleur levier de négociation." },
  { season:"toute_annee", category:"securite", title:"Phares : vérifiez leur alignement une fois par an", content:"Des phares mal alignés éclairent le mauvais endroit (trop haut, trop bas, ou de travers) et peuvent éblouir les autres conducteurs. L'alignement change après un choc ou un remplacement. Vérifiable en regardant le faisceau sur un mur plat à 7 m. Votre garagiste peut corriger l'alignement en quelques minutes pour peu de frais." },
  { season:"toute_annee", category:"entretien", title:"Câble de masse : la pièce oubliée qui cause des problèmes électriques", content:"Le câble de masse relie la batterie à la carrosserie et est essentiel pour tout le circuit électrique. Un câble oxydé ou desserré peut causer des problèmes électriques mystérieux : démarrage difficile, voyants aléatoires, consommation anormale. Vérifiez-le lors de chaque vidange — le remplacement coûte presque rien." },
  { season:"toute_annee", category:"entretien", title:"Joints de portière : un soin préventif simple", content:"Des joints de portière secs et durcis laissent entrer l'eau et le bruit, et peuvent coller par grand froid. Une application annuelle de silicone spray ou de glycérine les garde souples et prolonge leur durée de vie. Geste simple à faire lors du nettoyage printanier." },
  { season:"toute_annee", category:"economie", title:"Climatisation : l'impact sur la consommation est réel", content:"La climatisation peut augmenter la consommation de carburant de 10 à 20 %. Pour limiter cet impact : stationnez à l'ombre, ouvrez les fenêtres quelques secondes au départ pour évacuer l'air chaud avant d'allumer la clim, et réglez-la à 22-23 °C plutôt qu'au minimum. En ville à basse vitesse, les fenêtres ouvertes sont plus économiques." },
  { season:"toute_annee", category:"securite", title:"Conduite par temps de pluie : les bons réflexes", content:"La pluie est responsable de 70 % des accidents liés aux conditions météo. Augmentez votre distance de sécurité, réduisez votre vitesse de 20 %, évitez les freinages brusques. Si l'aquaplaning survient (perte de contact entre les pneus et la route), ne freinez pas et ne tournez pas brusquement — relâchez doucement l'accélérateur jusqu'à retrouver l'adhérence." },
  { season:"toute_annee", category:"electrique", title:"VE et grand froid québécois : maximisez votre autonomie", content:"Par -20 °C, l'autonomie d'un véhicule électrique peut chuter de 30 à 40 %. Préchauffez votre véhicule branché (pas sur la batterie), utilisez les sièges chauffants plutôt que le chauffage d'habitacle, et planifiez vos recharges. L'application de votre constructeur donne souvent l'autonomie estimée en temps réel selon la température." },
  { season:"toute_annee", category:"achat", title:"Garantie prolongée : vaut-elle le prix demandé ?", content:"Les garanties prolongées des concessionnaires sont souvent très profitables pour eux — et rarement pour vous. Étudiez : quels composants sont couverts (souvent pas les plus coûteux), quelles sont les exclusions, et chez qui vous devrez faire réparer. Une garantie du constructeur (pas du concessionnaire) avec un bon réseau vaut davantage. Résistez à la vente sous pression." },
  { season:"toute_annee", category:"entretien", title:"Nettoyez les contacts de votre batterie", content:"Une couche de corrosion blanche ou bleutée sur les bornes de batterie crée une résistance qui peut empêcher le démarrage. Nettoyez avec un mélange de bicarbonate de soude et d'eau, une vieille brosse à dents et des gants — la corrosion est chimiquement active. Protégez ensuite avec un spray anti-corrosion. Opération gratuite, résultats immédiats." },
  { season:"toute_annee", category:"securite", title:"Systèmes ADAS : comprenez leurs limites", content:"Les aides à la conduite modernes (maintien de voie, freinage automatique, régulateur adaptatif) ne remplacent pas votre attention. Ils peuvent être aveuglés par la neige, le soleil de face, des marquages usés ou une caméra sale. Gardez toujours les mains sur le volant et les yeux sur la route. Ces systèmes assistent, ils ne conduisent pas." },
  { season:"toute_annee", category:"entretien", title:"Nettoyer les injecteurs : quand et pourquoi ?", content:"Avec le temps, les injecteurs s'encrassent et atomisent moins bien le carburant, ce qui nuit aux performances et à la consommation. Un nettoyant injecteur ajouté au réservoir tous les 15 000 km est préventif. Si votre moteur manque de puissance ou consomme plus sans raison, un nettoyage professionnel aux ultrasons peut être envisagé." },
  { season:"toute_annee", category:"economie", title:"Carburant premium : en avez-vous vraiment besoin ?", content:"Si votre moteur n'exige pas d'essence premium (indice d'octane 91+), mettre du super n'apportera aucun bénéfice. Consultez votre manuel : « recommandé » n'est pas « exigé ». En revanche, si votre moteur exige du premium et que vous mettez de l'ordinaire, le calculateur moteur retardera l'allumage — moins de puissance et potentiellement plus de consommation." },
  { season:"toute_annee", category:"entretien", title:"Embrayage : les habitudes qui le font durer plus longtemps", content:"Si vous conduisez une voiture manuelle : ne reposez pas le pied sur la pédale d'embrayage en roulant (semi-engagement constant), n'utilisez pas l'embrayage pour tenir dans une côte (frein à main à la place), et ne faites pas patiner inutilement. Ces habitudes peuvent doubler la durée de vie de l'embrayage." },
  { season:"toute_annee", category:"securite", title:"Freinage d'urgence avec ABS : le bon geste", content:"Contrairement aux anciens freins, avec l'ABS vous devez appuyer fort et maintenir la pédale de frein enfoncée en situation d'urgence — ne pompez pas. L'ABS fait ce travail automatiquement, en modulant la pression pour éviter le blocage des roues et maintenir la direction. La sensation de vibration dans la pédale est normale." },
];

async function main() {
  const year = new Date().getFullYear();
  const startDate = nextMonday(new Date());

  // Supprime les conseils de l'année courante pour pouvoir relancer
  await prisma.autoTip.deleteMany({ where: { year } });

  // Distribue les 104 conseils sur 52 semaines (2 par semaine, lundi et jeudi)
  const shuffled = [...TIPS].sort(() => Math.random() - 0.5);
  // Rembobine si on n'a pas assez de conseils (on complète en répétant)
  while (shuffled.length < 104) shuffled.push(...TIPS.sort(() => Math.random() - 0.5));

  const records = [];
  for (let week = 0; week < 52; week++) {
    const monday = new Date(startDate);
    monday.setDate(startDate.getDate() + week * 7);
    monday.setHours(8, 0, 0, 0);

    const thursday = new Date(monday);
    thursday.setDate(monday.getDate() + 3);

    const tipA = shuffled[week * 2];
    const tipB = shuffled[week * 2 + 1];

    records.push({ ...tipA, publishAt: monday,   year, sentAt: null });
    records.push({ ...tipB, publishAt: thursday, year, sentAt: null });
  }

  await prisma.autoTip.createMany({ data: records });
  console.log(`✅ ${records.length} conseils créés pour ${year}`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
